<?php
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath() . '/public');
}

$nombreUsuario = 'SESION NO INICIADA';
$tipoUsuario = 'Usuario';
if ($sesionUsuario = $this->identity()) {
    $nombreUsuario = $this->escapeHtml($sesionUsuario->NOM_USU) . ' ' . $this->escapeHtml($sesionUsuario->APELL_USU);
    $tipoUsuario = $this->escapeHtml($sesionUsuario->TIPO_USUARIO);
    $sexo = $this->escapeHtml($sesionUsuario->SEXO);
    if ($sexo == 'Masculino') {
        $ao = 'o';
    } else {
        $ao = 'a';
    }
}

echo $this->doctype();
?>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php
        echo $this->headTitle('.:: POPGYM ::. ')->setSeparator(' - ')->setAutoEscape(false);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/custom.css'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
        echo $this->headScript()
                ->prependFile($this->basePath('js/jquery.smartWizard.js'))
                ->prependFile($this->basePath('js/nprogress.js'))
                ->prependFile($this->basePath('js/fastclick.js'))
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>
    </head>
    <body class="nav-md">
        <div class="container body">
            <div class="main_container">
                <?php echo $this->header; ?>
                <?php
                if ($tipoUsuario == 'Administrador') {
                    echo $this->menuadmin;
                } else if ($tipoUsuario == 'Cliente') {
                    echo $this->menu;
                } else if ($tipoUsuario == 'Asistencia'){
                    echo $this->menuasistencia;
                }
                ?>
                <div class="right_col" role="main">
                    <br />
                    <div class="">
                        <?php echo $this->content; ?>
                    </div>
                </div>
                <?php echo $this->footer; ?>
            </div>
        </div>
        <script src="/gimnasio/public/js/custom.js"></script>
    </body>
</html>
