<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/series-label.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>

<script type="text/javascript">

    Highcharts.chart('graficarMedidas', {

        title: {
            text: 'MEDIDAS'
        },

        subtitle: {
            text: 'POPGYM'
        },

        yAxis: {
            title: {
                text: 'Centimetros (cm)'
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },

        xAxis: {
            categories: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['fechaMedias'];
}
?>]
        },

        series: [{
                name: 'Peso',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getPESO();
}
?>]
            }, {
                name: 'Hombro',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getHOMBRO();
}
?>]
            }, {
                name: 'Pecho',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getPECHO();
}
?>]
            }, {
                name: 'Biceps',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getBICEPS();
}
?>]
            }, {
                name: 'Cintura',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getCINTURA();
}
?>]
            }, {
                name: 'Cadera',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getCADERA();
}
?>]
            }, {
                name: 'Pierna',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getCADERA();
}
?>]
            }, {
                name: 'Pantorrilla',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getPANTORRILLA();
}
?>]
            }, {
                name: '%GC',
                data: [<?php
foreach ($this->usuario as $usuario) {
    echo $usuario['medidasOBJ']->getPorGrasa();
}
?>]
            }
        ],

        responsive: {
            rules: [{
                    condition: {
                        maxWidth: 500
                    },
                    chartOptions: {
                        legend: {
                            layout: 'horizontal',
                            align: 'center',
                            verticalAlign: 'bottom'
                        }
                    }
                }]
        }

    });
</script>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Medidas De: <?php
                foreach ($this->usuario as $usuario) {
                    echo $usuario['usuarioOBJ']->getNOM_USU() . ' ' . $usuario['usuarioOBJ']->getAPELL_USU();
                }
                ?>
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Acciones
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="#">IMG: <?php
                                    foreach ($this->usuario as $usuario) {
                                        echo $usuario['medidasOBJ']->getIMC();
                                    }
                                    ?></a>
                            </li>
                            <li><a href="#">IGC</a>
                            </li>
                            <li><a href="#">%GC: <?php
                                    foreach ($this->usuario as $usuario) {
                                        echo $usuario['medidasOBJ']->getPGC();
                                    }
                                    ?></a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Progresos</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="graficarMedidas" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
<!--<script src="/gimnasio/public/js/highcharts.js"></script>
<script src="/gimnasio/public/js/modules/series-label.js"></script>
<script src="/gimnasio/public/js/modules/exporting.js"></script>
<script src="/gimnasio/public/js/modules/export-data.js"></script>-->