<?php
$title = 'Usuarios';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('/public/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('/public/css/green.css'));

$this->headScript()->prependScript('$(document).ready(function() {'
                . '$("#tblUsuarios").DataTable({'
                . 'responsive: true,'
                . '"iDisplayLength": 25,
                    "sPaginationType": "full_numbers",
                    "oLanguage": {
                        "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                        "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                        "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        "sInfoEmpty": "Mostrando 0 A 0 registros",
                        "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                        "sLoadingRecords": "CARGANDO...",
                        "sProcessing": "EN PROCESO...",
                        "sSearch": "Buscar:",
                        "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        "oPaginate": {
                            "sFirst": "Inicio",
                            "sLast": "Fin",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        }
                    },
                    "aaSorting": [[0, "asc"]]'
                . '});'
                . '});'
                , 'text/javascript'
                , array('noescape' => true))
        ->prependFile('/gimnasio/public/js/sistema/usuario.js')
        ->prependFile('/gimnasio/public/js/datatables.scroller.min.js')
        ->prependFile('/gimnasio/public/js/responsive.bootstrap.js')
        ->prependFile('/gimnasio/public/js/dataTables.responsive.min.js')
        ->prependFile('/gimnasio/public/js/buttons.bootstrap.min.js')
        ->prependFile('/gimnasio/public/js/dataTables.buttons.min.js')
        ->prependFile('/gimnasio/public/js/dataTables.bootstrap.min.js')
        ->prependFile('/gimnasio/public/js/jquery.dataTables.min.js');
?>
<!-- top tiles -->
<div class="row tile_count">
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Total Usuarios</span>
        <?php
        echo '<div class="count">' . $this->usuariosTotal . '</div>';
        ?>
        <span class="count_bottom"><i class="green">100% </i> En el sistema</span>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
        <div class="count">123.50</div>
        <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> En el sistema</span>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Total Hombres</span>
        <?php
        $this->usuariosTotal;
        $this->HombresTotal;
        $operH = ($this->HombresTotal * 100) / $this->usuariosTotal;
        echo '<div class="count">' . $this->HombresTotal . '</div>';
        if ($operH <= 25) {
            echo '<span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>';
        } else
            echo '<span class="count_bottom"><i class="green"><i class="fa fa-sort-desc"></i>';
        echo $operH . '%';
        echo '</i></span>';
        ?>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Total Mujeres</span>
        <?php
        $this->usuariosTotal;
        $this->MujeresTotal;
        $operM = ($this->MujeresTotal * 100) / $this->usuariosTotal;
        echo '<div class="count">' . $this->MujeresTotal . '</div>';
        if ($operM <= 25) {
            echo '<span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>';
        } else
            echo '<span class="count_bottom"><i class="green"><i class="fa fa-sort-desc"></i>';
        echo $operM . '%';
        echo '</i></span>';
        ?>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
        <div class="count">2,315</div>
        <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> En el sistema</span>
    </div>
    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
        <span class="count_top"><i class="fa fa-user"></i> Colecciones totales</span>
        <div class="count">7,325</div>
        <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> En el sistema</span>
    </div>
</div>
<!-- /top tiles -->
<div class="clearfix"></div>
<div class="row">
    <hr>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Registros del Sistema <small>Usuarios</small></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>    
                        <button type="button" onclick="verAgregarUsuario()" class="btn btn-success"><i class="fa fa-plus"></i> Registrar Usuario</button>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <p class="text-muted font-13 m-b-30">
                    A continuacion se listan todos los usuarios registrados en el sistema.
                </p>
                <table id="tblUsuarios" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NOMBRES</th>
                            <th>APELLIDOS</th>
                            <th>IDENTIFICACION</th>                           
                            <th>TELEFONO</th>
                            <th>TIPO USUARIO</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->usuarios as $usuario) {
                            echo '<tr>';
                            echo '<td>' . $usuario->getPk_usuario_id() . '</td>';
                            echo '<td>' . $usuario->getNOM_USU() . '</td>';
                            echo '<td>' . $usuario->getAPELL_USU() . '</td>';
                            echo '<td>' . $usuario->getIDENTIFICACION() . '</td>';
                            echo '<td>' . $usuario->getTEL_USU() . '</td>';
                            echo '<td>' . $usuario->getTIPO_USUARIO() . '</td>';
                            echo '<td>';
                            echo '<a href="" onclick="verEditar(' . $usuario->getPk_usuario_id() . '); return false;" title="Editar este Usuario"><i class="fa fa-edit"></i></a>';
                            echo '&nbsp;&nbsp;';
//                            echo '<a href="" onclick="verDetalle(' . $usuario->getPk_usuario_id() . '); return false;" title="Ver este Usuario a Detalle"><i class="fa fa-eye"></i></a>';
//                            echo '&nbsp;&nbsp;';
                            echo '<a href="#" title="DETALLE" onclick="detalleUsuario(' . $usuario->getPk_usuario_id() . '); return false; "> <i class="fa fa-eye"> </i> </a>';
                            echo '&nbsp;&nbsp;';
                            echo '<a href="#" title="MEDIDAS" onclick="medidasUsuario(' . $usuario->getPk_usuario_id() . '); return false; "> <i class="fa fa-bar-chart"> </i> </a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFormulario" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="overflow-y: scroll">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Formulario</h4>
            </div>
            <div class="modal-body">
                <div style="padding: 10px" class="container-fluid">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="x_panel">
                                <div class="x_content" id="divContenido"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <b>POPGYM &copy Copyright <?php echo date('Y/M/d'); ?></b>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="dlgDetalles" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                <img src="/gimnasio/public/img/logo.png" style="width: 8%" alt="Gimnasio"/>
                <h4 class="modal-title">POPGYM</h4>
            </div>
            <div class="modal-body" >
                <div id="divDetalle" class="row"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div>
            <div class="modal-footer">
                <b>POPGYM &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="dlgMedidas" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

                <img src="/gimnasio/public/img/logo.png" style="width: 8%" alt="POPGYM"/>
                <h4 class="modal-title">POPGYM</h4>
            </div>
            <div class="modal-body" >
                <div id="divMedidas" class="row"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
            </div>
            <div class="modal-footer">
                <b>POPGYM &copy Copyright <?php echo date('Y'); ?></b>
            </div>
        </div>
    </div>
</div>