<p class="text-muted font-13 m-b-30">
    A continuacion se listan todos las usuarios registrados en el sistema.
</p><br>
<div style="overflow: scroll">
    <table id="tblUsuarios" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>NOMBRES</th>
                <th>APELLIDOS</th>
                <th>IDENTIFICACION</th>
                <th>TIPO USUARIO</th>
                <th>ESTADO</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($this->usuarios as $usuario) {
                echo '<tr>';
                echo '<td>' . $usuario->getPk_usuario_id() . '</td>';
                echo '<td>' . $usuario->getNOM_USU() . '</td>';
                echo '<td>' . $usuario->getAPELL_USU() . '</td>';
                echo '<td>' . $usuario->getIDENTIFICACION() . '</td>';
                echo '<td>' . $usuario->getTIPO_USUARIO() . '</td>';
                echo '<td>' . $usuario->getESTADO() . '</td>';
                echo '<td>';
                echo '<a href="" onclick="selectUsuario(' . $usuario->getPk_usuario_id() . '); return false;" title="Seleccionar este Usuario"><i class="fa fa-check"></i></a>';
                echo '</td>';
                echo '</tr>';
            }
            ?>
        </tbody>
    </table>
</div>