<legend><b><i class="fa fa-paw"></i> Huella dactilar de:</b> <?php echo $this->imgHuella['nombreUsuario']; ?></legend>
<div align="center">
    <img src="data:image/png;base64, <?php echo $this->imgHuella['imgHuella']; ?>" alt="Huella no registrada" style="border: 15px solid; color:#2A3F54;">
</div>
<div class="ln_solid"></div>
<div class="form-group">
    <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-3">
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-close"></i> Cerrar</button>
    </div>
</div>