<?php
$nombreUsuario = 'SESION NO INICIADA';
$tipoUsuario = 'Usuario';
$hiddenCliente = '';
if ($sesionUsuario = $this->identity()) {
    $tipoUsuario = $this->escapeHtml($sesionUsuario->TIPO_USUARIO);
    $sexo = $this->escapeHtml($sesionUsuario->SEXO);
    if ($sexo == 'Masculino') {
        $ao = 'O';
    } else {
        $ao = 'A';
    }
    if ($tipoUsuario == 'Administrador') {
        $AdministradorUsuario = 'Administrador';
        $hiddenCliente = '';
    } else {
        $AdministradorUsuario = 'Usuario';
        $hiddenCliente = 'hidden';
    }
}
?>
<head>      
    <!-- FullCalendar -->
    <link href="/gimnasio/public/css/fullcalendar.min.css" rel="stylesheet">
    <link href="/gimnasio/public/css/fullcalendar.print.css" rel="stylesheet" media="print">
    <link href="/gimnasio/public/css/bootstrap-clockpicker.css" rel="stylesheet">
</head>

<style>
    .column {
        float: left;
        width: 33.33%;
        padding: 10px;
        height: 300px; /* Should be removed. Only for demonstration */
    }

</style>
<div class="x_content">

    <div class="" role="tabpanel" data-example-id="togglable-tabs">
        <ul id="myTab1" class="nav nav-tabs bar_tabs right" role="tablist">
            <li role="presentation" class="active"><a href="#tab_content11" id="home-tabb" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true"><i class="fa fa-home"></i> INICIO</a>
            </li>
            <li role="presentation" class=""><a href="#tab_content22" role="tab" id="profile-tabb" data-toggle="tab" aria-controls="profile" aria-expanded="false"><i class="fa fa-check-circle"></i> NUSTROS VALORES</a>
            </li>
            <li role="presentation" class=""><a href="#tab_content33" role="tab" id="profile-tabb3" data-toggle="tab" aria-controls="clases" aria-expanded="false"><i class="fa fa-calendar"></i> CLASES Y CUMPLEAÑOS</a>
            </li>
            <li role="presentation" class=""><a href="#tab_estadisticas" role="tab" id="profile-tabb4" data-toggle="tab" aria-controls="clases" aria-expanded="false"><i class="fa fa-bar-chart-o"></i> ESTADISTICAS</a>
            </li>
        </ul>
        <div id="myTabContent2" class="tab-content">
            <div role="tabpanel" class="tab-pane fade active in" id="tab_content11" aria-labelledby="home-tab">              
                <div class="profile_info">
                    <span><h1>POPGYM BIENVENID<?php echo $ao; ?> </h1></span>
                    <span><h3> <?php echo $AdministradorUsuario; ?></h3></span>
                </div>
                <div ALIGN=center>
                    <div class="container">
                        <br>
                        <div id="myCarousel" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#myCarousel" data-slide-to="1"></li>
                                <li data-target="#myCarousel" data-slide-to="2"></li>
                                <li data-target="#myCarousel" data-slide-to="3"></li>
                                <li data-target="#myCarousel" data-slide-to="4"></li>
                                <li data-target="#myCarousel" data-slide-to="5"></li>
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">

                                <div class="item active">
                                    <img src="/gimnasio/public/img/logo.png" style="width: 40%" alt="Gimnasio"/> <br><br>
                                    <div class="carousel-caption">
                                        <h3>Gym</h3>
                                        <p>Cuanto más sudas en el entrenamiento, menos sangras en combate.</p>
                                    </div>
                                </div>

                                <div class="item">
                                    <img src="/gimnasio/public/img/logoGym.jpg" alt="Gimnasio2" width="55%" height="100%">
                                    <div class="carousel-caption">
                                        <h3>Gym</h3>
                                        <p>Cuanto más sudas en el entrenamiento, menos sangras en combate.</p>
                                    </div>
                                </div>

                                <div class="item">
                                    <img src="/gimnasio/public/img/gimnasio2.jpg" alt="Flower" width="50%" height="25%">
                                    <div class="carousel-caption">
                                        <h3>Gym</h3>
                                        <p>La pasión triunfa sobre todo.</p>
                                    </div>
                                </div>

                                <div class="item">
                                    <img src="/gimnasio/public/img/gimnasio3.jpg" alt="Flower" width="65%" height="25%">
                                    <div class="carousel-caption">
                                        <h3>Gym</h3>
                                        <p>Cuida de tu cuerpo. Es el único lugar que tienes para vivir.</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="/gimnasio/public/img/gimnasio4.jpg" alt="Flower" width="60%" height="25%">
                                    <div class="carousel-caption">
                                        <h3>Gym</h3>
                                        <p>Siempre parece imposible hasta que se hace.</p>
                                    </div>
                                </div>
                                <div class="item">
                                    <img src="/gimnasio/public/img/gimnasio5.jpg" alt="Flower" width="60%" height="25%">
                                    <div class="carousel-caption">
                                        <h3>Gym</h3>
                                        <p>Siempre parece imposible hasta que se hace.</p>
                                    </div>
                                </div>

                            </div>

                            <!-- Left and right controls -->
                            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                    <p>GIMNASIO</p>
                    <p>&copy;2016 Todos los derechos reservados.</p>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="tab_content22" aria-labelledby="profile-tab">
                <div class="row">
                    <div class="column" >
                        <h1 class="page-header" style="color: #d98e3d; text-shadow: 1px 1px #efc614">MISIÓN</h1>


                        <li>Contribuir al desarrollo integral de los clientes mediante el diseño y la aplicación de un conjunto de servicios que fortalezcan la salud física y mental.</li>

                        <li>Ayudar a nuestros socios a crear y mantener una excelente condición física a través de la nutrición y programas de entrenamiento.</li>

                        <li>Inculcar en niños, jóvenes y adultos, el valor de la salud y el ejercicio.</li>

                        <li> Mejorar la calidad de vida de las comunidades a través de la filosofía del ejercicio, programas y productos de nutrición.</li>

                        <li> Participar proactivamente en el bienestar de las personas en su entorno social y laboral.</li>

                        <li>Brindar un servicio único y facilitar las herramientas del éxito.</li>
                    </div>
                    <div class="column">
                        <h1 class="page-header" style="color: #d98e3d; text-shadow: 1px 1px #efc614">VISIÓN</h1>


                        <li>Ser un gimnasio líder, brindando calidad y bienestar a nuestros miembros, generando valor humano y profesional a nuestra empresa, a nuestros colaboradores y a nuestra comunidad.</li>

                        <li>Ser la mejor opción deportiva en la ciudad de <b>Popayán</b>, por la excelencia en los servicios y la moderna aparatología, potenciando los procesos de servicio al cliente y la atención personalizada.</li>

                        <li> Ofrecer un ambiente ameno, accesible, práctico y estimulante, en el que todo socio pueda expresar su competencia física, mental y espiritual.</li>

                        <li> Optimizar los objetivos de captación y retención de socios, garantizando calidad y resultados tangibles.</li>

                        <li>Promover la integración familiar por medio de las actividades deportivas en un clima sano, alegre y positivo.</li>
                    </div>
                    <div class="column">
                        <h1 class="page-header" style="color: #d98e3d; text-shadow: 1px 1px #efc614">VALORES</h1>


                        <li>Apego a la filosofía de la salud y el bienestar</li>

                        <li>Profesionalismo</li>

                        <li>Eficacia en el logro de los objetivos</li>

                        <li> Eficacia en el uso de los recursos</li>

                        <li>Excelencia en servicios</li>

                        <li>Compromiso social</li>

                        <li>Compromiso ambiental</li>

                        <li>Comportamiento ético y moral</li>

                        <li>Respeto a la integridad de nuestros usuarios, empleados y proveedores.</li>
                    </div>
                </div>
            </div>
            <div role="tabpanel" class="tab-pane fade" id="tab_content33" aria-labelledby="profile-tab">                
                <!--contenido-->
                <!-- page content -->

                <div class="container">

                    <div class="row">
                        <div class="col-sm-0"></div>
                        <div class="col-sm-12"><div id='calendar'></div></div>
                        <div class="col-sm-0"></div>
                    </div>
                </div>
                <!-- /page content -->       

                <!-- Modal Evento-->
                <div id="CalenderModalNew" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title" id="tituloEvento">Nuevo Evento</h4>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">  
                                <div class="x_content" id="divContenido"></div>
                            </div>
                            <div class="modal-footer">    
                                <fieldset <?php echo $hiddenCliente; ?>>
                                    <button type="button"id="btnEliminarEvento"class="btn btn-danger">BORRAR</button>                                
                                </fieldset>
                            </div>
                        </div>
                    </div>
                </div>             
                <!-- //Modal Evento-->
            </div>  
            <div role="tabpanel" class="tab-pane fade" id="tab_estadisticas" aria-labelledby="profile-tab4">
                <!-- top tiles -->
                <div class="row tile_count">
                    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                        <span class="count_top"><i class="fa fa-user"></i> Total Usuarios</span>
                        <?php
                        echo '<div class="count">' . $this->usuariosTotal . '</div>';
                        ?>
                        <span class="count_bottom"><i class="green">100% </i> En el sistema</span>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                        <span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
                        <div class="count">123.50</div>
                        <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> En el sistema</span>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                        <span class="count_top"><i class="fa fa-user"></i> Total Hombres</span>
                        <?php
                        $this->usuariosTotal;
                        $this->HombresTotal;
                        $operH = ($this->HombresTotal * 100) / $this->usuariosTotal;
                        echo '<div class="count">' . $this->HombresTotal . '</div>';
                        if ($operH <= 25) {
                            echo '<span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>';
                        } else
                            echo '<span class="count_bottom"><i class="green"><i class="fa fa-sort-desc"></i>';
                        echo $operH . '%';
                        echo '</i></span>';
                        ?>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                        <span class="count_top"><i class="fa fa-user"></i> Total Mujeres</span>
                        <?php
                        $this->usuariosTotal;
                        $this->MujeresTotal;
                        $operM = ($this->MujeresTotal * 100) / $this->usuariosTotal;
                        echo '<div class="count">' . $this->MujeresTotal . '</div>';
                        if ($operM <= 25) {
                            echo '<span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>';
                        } else
                            echo '<span class="count_bottom"><i class="green"><i class="fa fa-sort-desc"></i>';
                        echo $operM . '%';
                        echo '</i></span>';
                        ?>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                        <span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
                        <div class="count">2,315</div>
                        <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> En el sistema</span>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
                        <span class="count_top"><i class="fa fa-user"></i> Colecciones totales</span>
                        <div class="count">7,325</div>
                        <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> En el sistema</span>
                    </div>
                </div>
                <!-- /top tiles -->

                <!--estadisticas-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="x_panel">
                            <div class="x_title">
                                <h2>Asistencias <small>En el mes</small></h2>
                                <div class="filter">
                                    <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                                        <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                                        <span>Enero 30, 2019 - Diciembre 28, 2019</span> <b class="caret"></b>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="x_content">
                                <div class="col-md-9 col-sm-12 col-xs-12">
                                    <div class="demo-container" style="height:280px">
                                        <div id="chart_plot_02" class="demo-placeholder"></div>
                                    </div>
                                    <div class="tiles">
                                        <div class="col-md-4 tile">
                                            <span>Total Sessions</span>
                                            <h2>231,809</h2>
                                            <span class="sparkline11 graph" style="height: 160px;">
                                                <canvas width="200" height="60" style="display: inline-block; vertical-align: top; width: 94px; height: 30px;"></canvas>
                                            </span>
                                        </div>
                                        <div class="col-md-4 tile">
                                            <span>Total Revenue</span>
                                            <h2>$231,809</h2>
                                            <span class="sparkline22 graph" style="height: 160px;">
                                                <canvas width="200" height="60" style="display: inline-block; vertical-align: top; width: 94px; height: 30px;"></canvas>
                                            </span>
                                        </div>
                                        <div class="col-md-4 tile">
                                            <span>Total Sessions</span>
                                            <h2>231,809</h2>
                                            <span class="sparkline11 graph" style="height: 160px;">
                                                <canvas width="200" height="60" style="display: inline-block; vertical-align: top; width: 94px; height: 30px;"></canvas>
                                            </span>
                                        </div>
                                    </div>

                                </div>

                                <div class="col-md-3 col-sm-12 col-xs-12">
                                    <div>
                                        <div class="x_title">
                                            <h2>Top Profiles</h2>
                                            <ul class="nav navbar-right panel_toolbox">
                                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                                </li>
                                                <li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                                    <ul class="dropdown-menu" role="menu">
                                                        <li><a href="#">Settings 1</a>
                                                        </li>
                                                        <li><a href="#">Settings 2</a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                                </li>
                                            </ul>
                                            <div class="clearfix"></div>
                                        </div>
                                        <ul class="list-unstyled top_profiles scroll-view">
                                            <li class="media event">
                                                <a class="pull-left border-aero profile_thumb">
                                                    <i class="fa fa-user aero"></i>
                                                </a>
                                                <div class="media-body">
                                                    <a class="title" href="#">Ms. Mary Jane</a>
                                                    <p><strong>$2300. </strong> Agent Avarage Sales </p>
                                                    <p> <small>12 Sales Today</small>
                                                    </p>
                                                </div>
                                            </li>
                                            <li class="media event">
                                                <a class="pull-left border-green profile_thumb">
                                                    <i class="fa fa-user green"></i>
                                                </a>
                                                <div class="media-body">
                                                    <a class="title" href="#">Ms. Mary Jane</a>
                                                    <p><strong>$2300. </strong> Agent Avarage Sales </p>
                                                    <p> <small>12 Sales Today</small>
                                                    </p>
                                                </div>
                                            </li>
                                            <li class="media event">
                                                <a class="pull-left border-blue profile_thumb">
                                                    <i class="fa fa-user blue"></i>
                                                </a>
                                                <div class="media-body">
                                                    <a class="title" href="#">Ms. Mary Jane</a>
                                                    <p><strong>$2300. </strong> Agent Avarage Sales </p>
                                                    <p> <small>12 Sales Today</small>
                                                    </p>
                                                </div>
                                            </li>
                                            <li class="media event">
                                                <a class="pull-left border-aero profile_thumb">
                                                    <i class="fa fa-user aero"></i>
                                                </a>
                                                <div class="media-body">
                                                    <a class="title" href="#">Ms. Mary Jane</a>
                                                    <p><strong>$2300. </strong> Agent Avarage Sales </p>
                                                    <p> <small>12 Sales Today</small>
                                                    </p>
                                                </div>
                                            </li>
                                            <li class="media event">
                                                <a class="pull-left border-green profile_thumb">
                                                    <i class="fa fa-user green"></i>
                                                </a>
                                                <div class="media-body">
                                                    <a class="title" href="#">Ms. Mary Jane</a>
                                                    <p><strong>$2300. </strong> Agent Avarage Sales </p>
                                                    <p> <small>12 Sales Today</small>
                                                    </p>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                <!--//estadisticas-->
            </div>


            <!-- /calendar modal -->
            <script>
                $(document).ready(function () {
                    $('#calendar').fullCalendar({
                        header: {
                            left: 'today,prev,next',
                            center: 'title',
                            right: 'month,basickWeek,basickDay,agendaWeek,agendaDay,listMonth'
                        },
                        dayClick: function (date, jsEvent, view) {
//                            $('#start').val(date.format());
                            $('#CalenderModalNew').modal();
                            var fecha = date.format();
                            var d = new Date(fecha);
                            guardarEvento();
                            ponerFecha(d);
                        },
                        events: [

<?php
foreach ($this->evento as $evento) {
    echo "{";
    echo "pk_evento_id:'" . $evento->getPk_evento_id() . "',";
    echo "title:'" . $evento->getTitle() . "',";
    echo "descripcion:'" . $evento->getDescripcion() . "',";
    echo "start:'" . $evento->getStart() . "',";
    echo "color:'" . $evento->getColor() . "',";
    echo "textColor:'" . $evento->getTextColor() . "',";
    echo "end:'" . $evento->getEnd() . "',";
    echo "},";
}
foreach ($this->usuarioCumple as $usuario) {
    $dia = date("d", strtotime($usuario->getFECHA_NAC_USU()));
    $mes = date("m", strtotime($usuario->getFECHA_NAC_USU()));
    $ano = date("Y");
    echo "{";
    echo "pk_usuario_id:'" . $usuario->getPk_usuario_id() . "',";
    echo "title:'Cumpleaños: " . $usuario->getNOM_USU() . "',";
    echo "descripcion:'Fiesta De Cunpleaños',";
    echo "start:'" . $ano . $mes . $dia . "',";
    echo "color:'#d5133f',";
    echo "textColor:'#ffffff',";
    echo "end:'" . $ano . $mes . $dia . "',";
    echo "},";
}
?>

                        ],
                        eventClick: function (calEvent, jsEvent, view, date) {
                            $('#CalenderModalNew').modal();
//                            H2
                            $('#tituloEvento').html(calEvent.start.format() + " - " + calEvent.end.format());
                            var id = calEvent.pk_evento_id;
                            var idUser = calEvent.pk_usuario_id;
                            editarEvento(id, idUser);
                            $('#btnEliminarEvento').click(function () {
                                borrarEvento(id);
                            });
                        },
                        editable: true,
                        eventDrop: function (calEvent, moverEvento) {
                            var id = calEvent.pk_evento_id;
                            var titulo = calEvent.title;
                            var des = calEvent.descripcion;
                            var fStart = calEvent.start.format();
                            var cColor = calEvent.color;
                            var tColor = calEvent.textColor;
                            var fEnd = calEvent.end.format();
                            alert(calEvent.title + "; se movio evento a: " + calEvent.start.format());
                            moverEvento(id, titulo, des, fStart, cColor, tColor, fEnd, true);
                        },
                    });
                });
            </script>
            <!-- FullCalendar -->
            <script src="/gimnasio/public/js/fullCalendar/moment.min.js"></script>
            <script src="/gimnasio/public/js/fullCalendar/fullcalendar.min.js"></script>
            <script src="/gimnasio/public/js/fullCalendar/es.js"></script>
            <script src="/gimnasio/public/js/fullCalendar/bootstrap-clockpicker.js"></script>
            <!-- Custom Theme Scripts -->
            <script src="/gimnasio/public/js/sistema/index.js"></script>
            <!-- /page content -->

            <!--fin contenido-->
        </div>
    </div>
</div>

</div>
