<p class="text-muted font-13 m-b-30">
    A continuacion se listan todas las opciones registradas en el sistema que no han sido anexadas al actual cuestionario.
</p><br>
<table id="tblSeleccionarOpcion" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>ID</th>
            <th>OPCION</th>
            <th>ESTADO</th>
            <th>REGISTRADO POR</th>
            <th>FECHA REGISTRO</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->opciones as $opcion) {
            echo '<tr>';
            echo '<td>' . $opcion->getPk_opcion_id() . '</td>';
            echo '<td>' . $opcion->getOpcion() . '</td>';
            echo '<td>' . $opcion->getEstado() . '</td>';
            echo '<td>' . $opcion->getRegistradoPor() . '</td>';
            echo '<td>' . $opcion->getFechaHoraReg() . '</td>';
            echo '<td>';
            echo '<a href="" onclick="selectOpcion(' . $opcion->getPk_opcion_id() . ', ' . $this->idPregunta . '); return false;" title="Seleccionar esta Opcion"><i class="fa fa-check"></i></a>';
            echo '</td>';
            echo '</tr>';
        }
        ?>
    </tbody>
</table>
