<?php
$form = $this->formLogin;
$form->prepare();
$form->setAttribute('action', $this->url('login/default', array('controller' => 'login', 'action' => 'login')));
echo $this->form()->openTag($form);
?>

<h1>BIENVENIDO a POPGYM</h1>
<div class="form-group has-feedback">
    <input type="text" name="login" class="form-control" placeholder="Usuario" required>
    <span class="glyphicon glyphicon-user form-control-feedback"></span>
</div>
<div class="form-group has-feedback">
    <input type="password" id="password" name="password" class="form-control" placeholder="Contraseña" required>
    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
</div>
<div>
    <input type="submit" class="btn btn-default submit" value="Iniciar Sesion">
    <a class="reset_pass" href="#">¿Has olvidado la cuenta?</a>
</div>
<div class="clearfix"></div>
<div class="separator">
    <div class="clearfix"></div>
    <br />
    <div>
        <img src="/gimnasio/public/img/logo.png" style="width: 50%" alt="Gimnasio"/> <br><br>
        <p>POPGYM</p>
        <p>&copy;2016 Todos los derechos reservados.</p>
    </div>
</div>
<?php echo $this->formElement($form->get('security')) ?>
<?php echo $this->form()->closeTag() ?>
