<?php
if ($sesionUsuario = $this->identity()) {
    $nombreUsuario = $this->escapeHtml($sesionUsuario->NOM_USU) . ' ' . $this->escapeHtml($sesionUsuario->APELL_USU);
}
$usuario = $this->usuario;
$title = 'Medias de ' . $nombreUsuario;
$this->headTitle($title);
$this->headScript()
        ->prependFile('/gimnasio/public/js/highcharts.js')
        ->prependFile('/gimnasio/public/js/modules/exporting.js');


$scriptGraficoMedidas = "
           $(function () {
    $('#graficoBarras').highcharts({
        title: {
            text: 'Medidas',
            x: -20 //center
        },
        subtitle: {
            text: 'POPGYM',
            x: -20
        },
        xAxis: {
            categories: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['fechaMedias'] . ",";
}
$scriptGraficoMedidas .= "]
        },
        yAxis: {
            title: {
                text: 'Centimetros (cm)'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
            valueSuffix: 'cm'
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: 'Peso',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getPESO() . ",";
}
$scriptGraficoMedidas .= "]
        }, {
            name: 'Hombro',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getHOMBRO() . ",";
}
$scriptGraficoMedidas .= "]
        },{
            name: 'Pecho',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getPECHO() . ",";
}
$scriptGraficoMedidas .= "]
        },{
            name: 'Biceps',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getBICEPS() . ",";
}
$scriptGraficoMedidas .= "]
        },
        {
            name: 'Antebrazo',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getANTEBRAZO() . ",";
}
$scriptGraficoMedidas .= "]
        },{
            name: 'Cintura',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getCINTURA() . ",";
}
$scriptGraficoMedidas .= "]
        },{
            name: 'Cadera',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getCADERA() . ",";
}
$scriptGraficoMedidas .= "]
        },{
            name: 'Pirena A',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getPIERNA() . ",";
}
$scriptGraficoMedidas .= "]
        },{
            name: 'Pirena B',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getPiernaB() . ",";
}
$scriptGraficoMedidas .= "]
        },{
            name: 'Pantorrilla',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getPANTORRILLA() . ",";
}
$scriptGraficoMedidas .= "]
        },{
            name: '%GC',
            data: [";
foreach ($this->medidas as $medida) {
    $scriptGraficoMedidas .= "" . $medida['medidasOBJ']->getPorGrasa() . ",";
}
$scriptGraficoMedidas .= "]
        },
        ]
    });
});
        ";
$this->headScript()->appendScript($scriptGraficoMedidas);
?>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> Medidas De:<?php echo $nombreUsuario; ?>
                <div class="pull-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            Acciones
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li><a href="#">IMG</a>
                            </li>
                            <li><a href="#">IGC</a>
                            </li>
                            <li><a href="#">%GC</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#">Progresos</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="graficoBarras" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>