<?php
$title = 'Reporte ';
$this->headTitle($title);
$this->headLink()->prependStylesheet($this->basePath('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'))
        ->prependStylesheet($this->basePath('vendors/iCheck/skins/flat/green.css'));

$this->headScript()->prependScript('$(document).ready(function() {'
                . '$("#tblMensualidades").DataTable({'
                . 'responsive: true,'
                . '"iDisplayLength": 25,
                    "sPaginationType": "full_numbers",
                    "oLanguage": {
                        "sLengthMenu": "Mostrar: _MENU_ registros por pagina",
                        "sZeroRecords": "NO SE HA ENCONTRADO INFORMACION",
                        "sInfo": "Mostrando <b>_START_</b> a <b>_END_</b> registros <br>TOTAL REGISTROS: <b>_TOTAL_</b> Registros</b>",
                        "sInfoEmpty": "Mostrando 0 A 0 registros",
                        "sInfoFiltered": "(Filtrados de un total de <b>_MAX_</b> registros)",
                        "sLoadingRecords": "CARGANDO...",
                        "sProcessing": "EN PROCESO...",
                        "sSearch": "Buscar:",
                        "sEmptyTable": "NO HAY INFORMACION DISPONIBLE PARA LA TABLA",
                        "oPaginate": {
                            "sFirst": "Inicio",
                            "sLast": "Fin",
                            "sNext": "Siguiente",
                            "sPrevious": "Anterior"
                        }
                    },
                    "aaSorting": [[0, "des"]]'
                . '});'
                . '});'
                , 'text/javascript'
                , array('noescape' => true))
        ->prependFile('/gimnasio/public/js/sistema/reportes.js')
        ->prependFile('/gimnasio/public/vendors/iCheck/icheck.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-scroller/js/dataTables.scroller.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-responsive/js/dataTables.responsive.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-buttons/js/dataTables.buttons.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-buttons/js/buttons.html5.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-buttons/js/buttons.print.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js')
        ->prependFile('/gimnasio/public/vendors/pdfmake/build/pdfmake.min.js')
        ->prependFile('/gimnasio/public/vendors/pdfmake/build/vfs_fonts.js')
        ->prependFile('/gimnasio/public/vendors/datatables.net/js/jquery.dataTables.min.js');
$formSalida = $this->formSalida;
echo $this->form()->openTag($formSalida);
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header" style="color: #d98e3d; text-shadow: 1px 1px #efc614">REPORTES EN EXEL Y PDF<img src="/gimnasio/public/img/iconos/excel.png"width="50" height="50"><img src="/gimnasio/public/img/iconos/pdf.png"width="50" height="50"></h1>
    </div>
</div>
<fieldset>
    <p class="text-muted font-13 m-b-30">
        A continuacion se pueden descargar los reportes en excel como son: Mensualidades, Ventas y Entrenos.
    </p>
</fieldset>
<div class="form-group"> 
    <div class="col-xs-2 col-md-2">
        <div class="form-group">
            <?php echo $this->formRow($formSalida->get('tipo_reporte')); ?>
        </div>
    </div>        
    <div class="row">
        <div class="col-xs-2 col-md-2">
            <div class="form-group">                              
                <?php echo $this->formRow($formSalida->get('fechaInicio')); ?>
            </div>
        </div>        
        <div class="col-xs-2 col-md-2">
            <div class="form-group">                                
                <?php echo $this->formRow($formSalida->get('fechaFin')); ?>
            </div>
        </div>     
        <div class="col-xs-4 col-md-4">            
            <br>
            <div class="btn-group">
                <button  type="button" class="btn btn-primary" name="botonFecha" id="botonFecha" onclick="downloadReporte()" value="Descargar" >Descargar &nbsp; <i class="fa fa-download" aria-hidden="true"></i> </button>
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="<?php echo $this->url('administracion/default', array('controller' => 'mensualidad', 'action' => 'barchart')) ?>"><i class="fa fa-line-chart"></i> Estadisticas</a>
                    </li>                              
                </ul>
            </div>
        </div>        
    </div>        
</div>   
<div class="row"></div>